### ISSUE TITLE
Transactions Format V2

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/golibs#31]
#### Types to support:

- Coin transfers
- Token transfers
- Swaps (from to asset)
- Staking (delegations / undelegations), claim rewards, vote ... redelegating
- Smart contract calls (deposit, claim) - function name + values, raw data
- Pre build actions. Approve asset 1. 
- Collectibles Transfers
- Governance Vote #1 Yes/No.
- DEX (New, Cancel, Execute, Fill)

#### Small use cases:
- Lending (Borrow n AAVE, Lend 20 COMP, MINT 102 SPX)
- Provide liquidity pool ETH<>DAI
- Deposit funds to L2 network (could live in smart contract)

### Discussion points
- How to support any action format?
- How to localize?
- How to add new events and stay compatible? 

#### Additional support for:
- transactions types
- offset and limit - (pagination)
- timestamp
- versioning

`/transactions?types=transfer|token_transfer&from_timestamp=123&version=3&page=1&limit=10`

Old Coin Transfer:
```json
{
   "id":"0x05a9c7b75f57d7489dc143eb51600315439a324cdc2f749a27b99d7d395a7fe5",
   "coin":10000714,
   "from":"0x4982085C9e2F89F2eCb8131Eca71aFAD896e89CB",
   "to":"0x377E196Acd9215A881fc101A64AAa6CA0b0a75D6",
   "fee":"441000000000000",
   "date":1611012545,
   "block":4110960,
   "status":"completed",
   "sequence":12604,
   "type":"transfer",
   "direction":"outgoing",
   "memo":"",
   "metadata":{
      "value":"2000000000000000",
      "symbol":"BNB",
      "decimals":18
   }
}
```

New Coin Transfer Format:

```json
{
   "id":"0x05a9c7b75f57d7489dc143eb51600315439a324cdc2f749a27b99d7d395a7fe5",
   "asset_id":"c714",
   "from":"0x4982085C9e2F89F2eCb8131Eca71aFAD896e89CB",
   "to":"0x377E196Acd9215A881fc101A64AAa6CA0b0a75D6",
   "fee": {
        "asset": "c714_cTWT",
        "value": "441000000000000"
    },
   "date":1611012545,
   "block":4110960,
   "status":"completed",
   "sequence":12604,
   "direction":"outgoing",
   "memo":"",
}
```

```
   "transfers": [{
       "from":"0x4982085C9e2F89F2eCb8131Eca71aFAD896e89CB",
       "to":"0x377E196Acd9215A881fc101A64AAa6CA0b0a75D6",
       "asset": "c714",
       "value":"2000000000000000",
   }]
  "swaps": [{
          "from": {
              "address": "0x4982085C9e2F89F2eCb8131Eca71aFAD896e89CB"
               "asset": "c714"
              "value":"2000000000000000",
          },
          "to": {
               "address": "0x377E196Acd9215A881fc101A64AAa6CA0b0a75D6"
               "asset": "c714"
              "value":"2000000000000000",
          }
   }],
   "smart_contract_call": {

   }
```

`status`: `pending`, `completed`, `error`

**Comment by vikmeup** [comment]
Old Token Transfer:
```json
{
   "id":"0xbe2a68a6af062f6d8cf60558732f75ca66c63e95515121c1b681a5edd29b442f",
   "coin":10000714,
   "from":"0x631Fc1EA2270e98fbD9D92658eCe0F5a269Aa161",
   "to":"0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE",
   "fee":"1022300000000000",
   "date":1604602284,
   "block":1976580,
   "status":"completed",
   "sequence":303133,
   "type":"token_transfer",
   "direction":"incoming",
   "memo":"",
   "metadata":{
      "name":"XRP Token",
      "symbol":"XRP",
      "token_id":"0x1D2F0da169ceB9fC7B3144628dB156f3F6c60dBE",
      "decimals":18,
      "value":"101759200000000000000",
      "from":"0x631Fc1EA2270e98fbD9D92658eCe0F5a269Aa161",
      "to":"0xF706dc241a9BF1E4930ceF9f49ca4D5A22086F9C"
   }
}
```

**Comment by vikmeup** [comment]
Transfer (either regular native or token transfer)

```
{
   "id":"0x05a9c7b75f57d7489dc143eb51600315439a324cdc2f749a27b99d7d395a7fe5",
   "from":"0x4982085C9e2F89F2eCb8131Eca71aFAD896e89CB",
   "to":"0x377E196Acd9215A881fc101A64AAa6CA0b0a75D6",
   "type": "transfer",
   "date":1611012545,
   "block":4110960,
   "status":"completed",
   "sequence":12604,
   "direction":"outgoing",
   "memo":"",
   "metadata" : {
        "asset_id":"c714",
        "value: 1000000
    }, 
    "fee": {
        "asset": "c714_cTWT",
        "value": "441000000000000"
    },
}
```

**Comment by ivan-bozhytksyi** [comment]
The new transactions format is described in [notion](https://www.notion.so/trustwallet/Transactions-Spec-Draft-4645687e6f14467d85e4be6c33c26d97?d=5b82b427-310b-4e1c-97d8-dc916b5b4844#413b9f75bf1d4a0da85affb3654cf7c7)
Already supported list of blockchains is available in [postman](https://trustwallet.postman.co/workspace/Team-Workspace~0d8432a1-0039-461e-81a7-cc6962a36663/folder/10111942-44b0fa63-2714-4c58-9d45-3c0ccab1c244)

**Comment by ivan-bozhytksyi** [comment]
@vikmeup the proxy needs to be configured to allow API calls on `v1` route.
Mobile integration implementation can be started already. 
@madcake FYI ^^

**Comment by ivan-bozhytksyi** [comment]
UPD.
1. [Blockchains supported features (Notion) ](https://www.notion.so/trustwallet/e8983179c3e645a8aaf5693ea1e73fa5?v=2ceb2f5f06c14adfa07b092d59200e9b)
2. [Transaction types specification (Notion)](https://www.notion.so/trustwallet/Transactions-Spec-4645687e6f14467d85e4be6c33c26d97)

Currently, most of the requirements for this task are completed. 
Transaction types are supported for Version 1. Other types will be supported within related tasks in atlas.
