### ISSUE TITLE
Generate coins based on wallet core config

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/golibs#62]
https://github.com/trustwallet/golibs/blob/master/coin/coins.go

Ideally we should include all coins from here: https://github.com/trustwallet/wallet-core/blob/master/coins.json

**Comment by ivan-bozhytksyi** [comment]
@vikmeup Can we extend coint.json in wallet-core with such values as blockTime and minConfirmations so we can use it as complete source of the coins?

**Comment by vikmeup** [comment]
> @vikmeup Can we extend coins.json in wallet-core with such values as blockTime and minConfirmations so we can use it as complete source of the coins?

preferably to keep it outside of `coins.json` if possible, unless @hewigovens thinks otherwise
